version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name:              docker-compose build
          command:           docker-compose build
  # 順番を制御するworkflow
  workflows:
    build_and_test_and_deploy:
      jobs:
        - build
        - test:
          requires:
            - build